### ISSUE TITLE
Picture missing after changing subdomain

### ISSUE THREAD

**Issue by Jim-Young** [robiso/summernote-editor#11]
First thank you very much for this handy editor, it makes everything easy.

There is one problem after I changed subdomain/domain to a different one, all those uploaded pictures are missing. By viewing the sourcecode, I found it still used the old subdomain, then, I noticed when you added a new picture, it adds the full URL including the domain.

Like this:
`<img src="http://test1.example.com.au/data/files/Selection_001.png">`

Is there a way we insert the picture and it works like this:

`<img src="/data/files/Selection_001.png">`

Thanks again.

**Comment by robiso** [comment]
Hello @Jim-Young, happy to hear awesome feedback.

This isn't a bad idea in itself, however if you're going to be displaying images on subpages or have nested pages/subdomains, you could come into a situation where the images wouldn't be displaying correctly due to the incorrect /data folder path.

The easiest way to fix this is to open the page where the images aren't displayed correctly and fix the URL's manually to make the broken images work.

**Comment by Jim-Young** [comment]
Thanks for getting back to me. Alright, I'll probably just find/replace in that data file. Thanks again.
