### ISSUE TITLE
[Bug] Dropdown menus don't work on Paper L theme.

### ISSUE THREAD

**Issue by Imerion** [robiso/summernote-editor#15]
When using the summernote editor on the Paper L theme I can't seem to use the dropdowns for Style, Font Size, Table, etc. Everything else, including modal dialogs for Images and Links, work as expected.

Everything works well when switching the another theme, so I don't think it is related to this particular installation but rather have something to do with the Paper L theme.

**Comment by robiso** [comment]
Hello @Imerion. After some debugging, this seems to be a theme issue and not a Summernote issue.

I've updated both paper-l and paper-p themes to include the fix.
The issue was Summernote loads it's own bootstrap.min.js and so do these themes. The quick fix was to load the theme bootstrap only if the user is a visitor, since the admin already gets the bootstrap when Summernote is loaded.

Thanks for reporting!

**Comment by robiso** [comment]
Edit: Forgot to add, login to your WonderCMS website and check for updates, the fixed theme(s) should be there.
If you notice any issues after updating, feel free to write here or open a new issue on the theme itself.

**Comment by Imerion** [comment]
Fantastic, thanks!
